// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activity": {
            "get": {
                "description": "Get views and downloads over time",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get daily activity",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 7,
                        "description": "Number of days",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Daily activity",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repository.DailyActivity"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid days",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/documents/popular": {
            "get": {
                "description": "Get most viewed/downloaded documents",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get top documents",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Top documents",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repository.DocumentStats"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/overview": {
            "get": {
                "description": "Get total views and downloads",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get overview stats",
                "responses": {
                    "200": {
                        "description": "Overview stats",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "repository.DailyActivity": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "downloads": {
                    "type": "integer"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "repository.DocumentStats": {
            "type": "object",
            "properties": {
                "document_id": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "title": {
                    "description": "Note: We might not store title here, need to fetch or trust upstream",
                    "type": "string"
                },
                "view_count": {
                    "type": "integer"
                }
            }
        },
        "response.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/response.ErrorInfo"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8087",
	BasePath:         "/api/v1/analytics",
	Schemes:          []string{},
	Title:            "Analytics Service API",
	Description:      "API for system analytics and statistics",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
